services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: machi11_mama_couture_mongo_dev
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGODB_INITDB_DATABASE=machi11_mama_couture_dev

volumes:
  mongodb_data:
